name: clean_architeture_project
description: Clean arch project template to future projects.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.1.0
  get_storage: ^2.1.1
  flutter_modular: ^6.3.2
  dio: ^5.3.3
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  material_design_icons_flutter: ^7.0.7296
  flutter_easyloading: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  
flutter:
  uses-material-design: true

  assets:
    - lib/core/assets/images/
    - .env